site_name: ""
site_url: https://dqx-translation-project.github.io
copyright: maintained by serany

plugins:
  - glightbox  # add image zoom functionality
  - search

nav:
  - welcome: index.md
  - dqxclarity:
    - install: dqxclarity.md
    - troubleshooting: troubleshooting.md
    - apis:
      - deepl: dqxclarity/apis/deepl.md
      - google: dqxclarity/apis/google_api.md
  - faq: faq/index.md

theme:
  name: material
  favicon: asset/favicon.ico
  custom_dir: overrides
  font:
    text: Varela Round
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - content.tooltips
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dqx-translation-project
      name: GitHub
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/dragonquestx"
      name: DQX Worldwide
    - icon: bootstrap/kofi
      link: https://ko-fi.com/serany
      name: serany on Ko-fi
